import turtle
ventana = turtle.Screen()
soplete=turtle.Turtle()
soplete.shape("turtle")
soplete.color("fuchsia")
soplete.width (2)
soplete.fd(100)
soplete.left(90)
soplete.fd(100)
soplete.left(90)
soplete.fd(100)
soplete.left(90)
soplete.fd(100)
turtle.done()